Feat: BatchReplayer additional database targets
aws-samples/aws-analytics-reference-architecture pull request #513
Opened 2022-12-04 18:33 UTC by dairiley

Issue #, if available: [#385](https://github.com/aws-samples/aws-analytics-reference-architecture/issues/385)

Description of changes: Add optional database targets for Amazon RDS MySQL, Amazon RDS Postgres, Amazon Aurora, Amazon Redshift and Amazon DynamoDB to `BatchReplayer` and make `sinkBucket` an optional target.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-01-02 15:30 UTC, vgkowski requested changes

2023-01-02 15:30 UTC, vgkowski commented on core/src/data-generator/batch-replayer.ts
> +  public readonly databaseVpcSG?: ISecurityGroup;
create a dedicated security group for the BatchReplayer instead of reusing the DB sec group

2023-01-12 11:55 UTC, lmouhib requested changes
Left comments for changes

2023-02-16 17:25 UTC, dairiley commented
I've made updates in line with your feedback above, please re-review.

2023-03-10 20:12 UTC, vgkowski approved these changes

2023-03-10 20:14 UTC, merged